services:
  - type: web
    name: cbb-edge-finder-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CBBD_API_KEY
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
